/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import MySQL.MySQLDaoManager;
import com.sun.javafx.scene.control.skin.VirtualFlow;
import dao.DAOException;
import dao.DAOManager;
import dao.ItemCalatalogoDAO;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.Catalogo;
import modelo.Cliente;
import modelo.DetallePedidoCliente;
import modelo.DetallePresupuesto;
import modelo.ItemCatalogo;
import modelo.PedidoCliente;
import modelo.Presupuesto;
import modelo.Proveedor;

/**
 *
 * @author Lucas
 */
public class ventVenta extends javax.swing.JFrame {

    private static DAOManager manager;
    Cliente clientePedidoPresupuesto = null;
    List<DetallePresupuesto> listDetalle = new ArrayList<>();
    List<Cliente> listaCliente = new ArrayList<>();

    /**
     * Creates new form vtcompra
     */
    public ventVenta(DAOManager manager) throws SQLException {
        ventVenta.manager = manager;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoVentaSinPresupuesto = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresoDniCliente = new javax.swing.JTextField();
        botonBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        DialogoGenerarPresupuesto = new javax.swing.JDialog();
        DialogoVentaConPresupuesto = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtIDPresupuesto = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        labelFailedPresupuesto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePresupuesto = new javax.swing.JTable();
        btnAtrasVentaPresupuesto = new javax.swing.JButton();
        btnSiguienteVentaPresupuesto = new javax.swing.JButton();
        dialogVentaConPresupuestoOne = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        btnSiguienteVPO = new javax.swing.JButton();
        txtDniCliente = new javax.swing.JTextField();
        btnAtrasVCPO = new javax.swing.JButton();
        dialogVentaConPresupuestoTwo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreClientePP = new javax.swing.JTextField();
        txtDniClientePP = new javax.swing.JTextField();
        txtDireccionClientePP = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePedidoPresupuesto = new javax.swing.JTable();
        btnAtrasVPT = new javax.swing.JButton();
        btnGenerarPedido = new javax.swing.JButton();
        dialogFailed = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jLabel3.setText("Realizar Pedido");

        jLabel4.setText("DNI Cliente:");

        ingresoDniCliente.setText(" ");
        ingresoDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDniClienteActionPerformed(evt);
            }
        });

        botonBuscarCliente.setText("Buscar");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jTextField1.setText(" ");

        jLabel5.setText("Direccion ");

        jTextField3.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ingresoDniCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscarCliente)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ingresoDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Telefono", "Email"
            }
        ));
        jScrollPane4.setViewportView(TablaCliente);

        javax.swing.GroupLayout DialogoVentaSinPresupuestoLayout = new javax.swing.GroupLayout(DialogoVentaSinPresupuesto.getContentPane());
        DialogoVentaSinPresupuesto.getContentPane().setLayout(DialogoVentaSinPresupuestoLayout);
        DialogoVentaSinPresupuestoLayout.setHorizontalGroup(
            DialogoVentaSinPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DialogoVentaSinPresupuestoLayout.setVerticalGroup(
            DialogoVentaSinPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoVentaSinPresupuestoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoGenerarPresupuestoLayout = new javax.swing.GroupLayout(DialogoGenerarPresupuesto.getContentPane());
        DialogoGenerarPresupuesto.getContentPane().setLayout(DialogoGenerarPresupuestoLayout);
        DialogoGenerarPresupuestoLayout.setHorizontalGroup(
            DialogoGenerarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DialogoGenerarPresupuestoLayout.setVerticalGroup(
            DialogoGenerarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(TxtIDPresupuesto);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Ingrese el ID del Presupuesto");

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tablePresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre - Descripcion", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePresupuesto);

        btnAtrasVentaPresupuesto.setText("Atras");

        btnSiguienteVentaPresupuesto.setText("Siguiente");
        btnSiguienteVentaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteVentaPresupuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogoVentaConPresupuestoLayout = new javax.swing.GroupLayout(DialogoVentaConPresupuesto.getContentPane());
        DialogoVentaConPresupuesto.getContentPane().setLayout(DialogoVentaConPresupuestoLayout);
        DialogoVentaConPresupuestoLayout.setHorizontalGroup(
            DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoVentaConPresupuestoLayout.createSequentialGroup()
                .addGroup(DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoVentaConPresupuestoLayout.createSequentialGroup()
                        .addComponent(labelFailedPresupuesto)
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DialogoVentaConPresupuestoLayout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoVentaConPresupuestoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DialogoVentaConPresupuestoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnAtrasVentaPresupuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                .addComponent(btnSiguienteVentaPresupuesto)
                .addGap(467, 467, 467))
        );
        DialogoVentaConPresupuestoLayout.setVerticalGroup(
            DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoVentaConPresupuestoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(34, 34, 34)
                .addGroup(DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFailedPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(DialogoVentaConPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasVentaPresupuesto)
                    .addComponent(btnSiguienteVentaPresupuesto))
                .addGap(36, 36, 36))
        );

        jLabel7.setText("Dni Cliente:");

        btnSiguienteVPO.setText("Generar Pedido");
        btnSiguienteVPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteVPOActionPerformed(evt);
            }
        });

        txtDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniClienteActionPerformed(evt);
            }
        });

        btnAtrasVCPO.setText("Atras");

        javax.swing.GroupLayout dialogVentaConPresupuestoOneLayout = new javax.swing.GroupLayout(dialogVentaConPresupuestoOne.getContentPane());
        dialogVentaConPresupuestoOne.getContentPane().setLayout(dialogVentaConPresupuestoOneLayout);
        dialogVentaConPresupuestoOneLayout.setHorizontalGroup(
            dialogVentaConPresupuestoOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogVentaConPresupuestoOneLayout.createSequentialGroup()
                .addGroup(dialogVentaConPresupuestoOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogVentaConPresupuestoOneLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogVentaConPresupuestoOneLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnSiguienteVPO))
                    .addGroup(dialogVentaConPresupuestoOneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnAtrasVCPO)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        dialogVentaConPresupuestoOneLayout.setVerticalGroup(
            dialogVentaConPresupuestoOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogVentaConPresupuestoOneLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(dialogVentaConPresupuestoOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnSiguienteVPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnAtrasVCPO)
                .addContainerGap())
        );

        jLabel8.setText("Pedido");

        jLabel9.setText("Nombre: ");

        jLabel10.setText("Dni:");

        jLabel11.setText("Direccion: ");

        txtNombreClientePP.setEditable(false);
        txtNombreClientePP.setText("jTextField4");

        txtDniClientePP.setEditable(false);
        txtDniClientePP.setText("jTextField4");

        txtDireccionClientePP.setEditable(false);
        txtDireccionClientePP.setText("jTextField4");

        tablePedidoPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre - Descripcion", "Precio Unitario", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablePedidoPresupuesto);

        btnAtrasVPT.setText("Atras");

        btnGenerarPedido.setText("Generar Pedido");
        btnGenerarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogVentaConPresupuestoTwoLayout = new javax.swing.GroupLayout(dialogVentaConPresupuestoTwo.getContentPane());
        dialogVentaConPresupuestoTwo.getContentPane().setLayout(dialogVentaConPresupuestoTwoLayout);
        dialogVentaConPresupuestoTwoLayout.setHorizontalGroup(
            dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel8))
                    .addGroup(dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                        .addGroup(dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                                .addComponent(txtNombreClientePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniClientePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDireccionClientePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnAtrasVPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarPedido)
                .addContainerGap())
        );
        dialogVentaConPresupuestoTwoLayout.setVerticalGroup(
            dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogVentaConPresupuestoTwoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreClientePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniClientePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDireccionClientePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(dialogVentaConPresupuestoTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasVPT)
                    .addComponent(btnGenerarPedido))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogFailedLayout = new javax.swing.GroupLayout(dialogFailed.getContentPane());
        dialogFailed.getContentPane().setLayout(dialogFailedLayout);
        dialogFailedLayout.setHorizontalGroup(
            dialogFailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        dialogFailedLayout.setVerticalGroup(
            dialogFailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Venta sin presupuesto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Venta con presupuesto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Generar presupuesto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar tipo de Venta");

        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(105, 105, 105)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(68, 68, 68)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogoVentaSinPresupuesto.setTitle("Ventana de Pedido sin presupuesto");
        DialogoVentaSinPresupuesto.setVisible(true);
        DialogoVentaSinPresupuesto.setSize(800, 500);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogoVentaConPresupuesto.setTitle("Ventana Sin Presupuesto");
        DialogoVentaConPresupuesto.setVisible(true);
        DialogoVentaConPresupuesto.setSize(800, 500);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        String cliente;
        cliente = ingresoDniCliente.getText();
        try {
            listaCliente = manager.getClienteDAO().obtenerTodos();
            
        } catch (DAOException ex) {
            Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void setTablaClientexDNI(){ 
        TablaCliente.removeAll();
        
        String[] columnas = new String[]{
            "Nombre",
            "Direccion",
            "Telefono",
            "Email"
        };
        
        final Class[] tiposColumnas = new Class[]{
           java.lang.String.class,
           java.lang.String.class,
           int.class,
           java.lang.String.class           
        };
        
        Object[][] datos = new Object[listaCliente.size()][4];
        int i = 0;
        
        for(Cliente c : listaCliente) {
            datos[i][0] = c.getNombre();
            datos[i][1] = c.getDireccion();
            datos[i][2] = c.getTelefono();
            datos[i][3] = c.getEmail();
            i++;
        }
        
        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                 return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            vtnPresupuesto ventanaVenta;
            ventanaVenta = new vtnPresupuesto(manager);
            ventanaVenta.setVisible(true);
            ventanaVenta.setSize(800, 500);

            this.dispose();

            DialogoGenerarPresupuesto.setTitle("Generar Presupuesto");

        } catch (DAOException ex) {
            Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        home ventaHome;
        try {
            ventaHome = new home();
            ventaHome.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
        java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
        Long ID = Long.valueOf(TxtIDPresupuesto.getText());
        Presupuesto p = null;
        try {
            p = manager.getPresupuestoDAO().obtener(ID);
        } catch (DAOException ex) {
            Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (p == null) {
            labelFailedPresupuesto.setText("Presupuesto Inexistente");
        } else {
            int dias = (int) ((sqlDate.getTime() - p.getFecha().getTime()) / 86400000);
            if (dias > 30) {
                labelFailedPresupuesto.setText("Presupuesto sin validez");
            } else {
                try {
                    listDetalle = manager.getDetallePresupuestoDAO().obtenerXIdPresupuesto(p.getIdPresupuesto());
                } catch (DAOException ex) {
                    Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
                }
                setTablePresupuesto(listDetalle);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSiguienteVentaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteVentaPresupuestoActionPerformed
        // TODO add your handling code here:
        dialogVentaConPresupuestoOne.setVisible(true);
        dialogVentaConPresupuestoOne.setSize(400, 300);
        dialogVentaConPresupuestoOne.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSiguienteVentaPresupuestoActionPerformed

    private void txtDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniClienteActionPerformed

    private void btnSiguienteVPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteVPOActionPerformed
        // TODO add your handling code here:

        Long dni = Long.valueOf(txtDniCliente.getText());
        try {
            clientePedidoPresupuesto = manager.getClienteDAO().obtener(dni);
        } catch (DAOException ex) {
            Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (clientePedidoPresupuesto == null) {
            ;
        }
        dialogVentaConPresupuestoTwo.setVisible(true);
        dialogVentaConPresupuestoTwo.setSize(800, 500);
        dialogVentaConPresupuestoTwo.setLocationRelativeTo(null);
        txtNombreClientePP.setText(clientePedidoPresupuesto.getNombre());
        txtDireccionClientePP.setText(clientePedidoPresupuesto.getDireccion());
        txtDniClientePP.setText(String.valueOf(clientePedidoPresupuesto.getTelefono()));
        setTablePedidoPresupuesto();
    }//GEN-LAST:event_btnSiguienteVPOActionPerformed

    private void btnGenerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPedidoActionPerformed
        // TODO add your handling code here:
        LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
        java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
        double total = 0;
        for (DetallePresupuesto dp : listDetalle) {
            total = total + dp.getSubtotal();
        }
        PedidoCliente pedido = new PedidoCliente(null, "En espera", total,
                sqlDate, sqlDate, clientePedidoPresupuesto.getdni());
        try {
            manager.getPedidoClienteDAO().insertar(pedido);
        } catch (DAOException ex) {
            Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        Long idPC = pedido.getIdPedidoCliente();
        for (DetallePresupuesto dp : listDetalle) {
            DetallePedidoCliente nuevo = new DetallePedidoCliente(
                    idPC, dp.getId().getIdMaterial(), dp.getDescripcion(),
                    (float) dp.getSubtotal(), dp.getCantidad());
            try {
                manager.getDetallePedidoDAO().insertar(nuevo);
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnGenerarPedidoActionPerformed

    private void ingresoDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoDniClienteActionPerformed

    private void setTablePedidoPresupuesto() {
        tablePedidoPresupuesto.removeAll();

        String[] columnas = new String[]{
            "Nombre - Descripcion",
            //"Precio Unitario",
            "Cantidad",
            "Subtotal"
        //"Seleccionar"
        };

        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            int.class,
            java.lang.Long.class, //JButton.class
        };
        Object[][] datos = new Object[listDetalle.size()][3];
        int i = 0;

        for (DetallePresupuesto m : listDetalle) {
            datos[i][0] = m.getDescripcion();
            datos[i][1] = m.getCantidad();
            datos[i][2] = m.getSubtotal();
            //datos[i][3] = m.getPrecioUnitario(); Mantenimiento
            i++;
        }
        tablePedidoPresupuesto.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return false;
            }
        });
    }

    private void setTablePresupuesto(List<DetallePresupuesto> listDetalle) {
        tablePresupuesto.removeAll();

        String[] columnas = new String[]{
            "Nombre - Descripcion",
            "Cantidad",
            "Subtotal"
        //"Seleccionar"
        };

        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            int.class,
            java.lang.Long.class, //JButton.class
        };
        Object[][] datos = new Object[listDetalle.size()][3];
        int i = 0;

        for (DetallePresupuesto m : listDetalle) {
            datos[i][0] = m.getDescripcion();
            datos[i][1] = m.getCantidad();
            datos[i][2] = m.getSubtotal();
            i++;
        }
        tablePresupuesto.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return false;
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ventVenta(manager).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogoGenerarPresupuesto;
    private javax.swing.JDialog DialogoVentaConPresupuesto;
    private javax.swing.JDialog DialogoVentaSinPresupuesto;
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTextPane TxtIDPresupuesto;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton btnAtrasVCPO;
    private javax.swing.JButton btnAtrasVPT;
    private javax.swing.JButton btnAtrasVentaPresupuesto;
    private javax.swing.JButton btnGenerarPedido;
    private javax.swing.JButton btnSiguienteVPO;
    private javax.swing.JButton btnSiguienteVentaPresupuesto;
    private javax.swing.JDialog dialogFailed;
    private javax.swing.JDialog dialogVentaConPresupuestoOne;
    private javax.swing.JDialog dialogVentaConPresupuestoTwo;
    private javax.swing.JTextField ingresoDniCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelFailedPresupuesto;
    private javax.swing.JTable tablePedidoPresupuesto;
    private javax.swing.JTable tablePresupuesto;
    private javax.swing.JTextField txtDireccionClientePP;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtDniClientePP;
    private javax.swing.JTextField txtNombreClientePP;
    // End of variables declaration//GEN-END:variables
}
