/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dao.DAOException;
import dao.DAOManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import modelo.Cliente;
import vistas.DetallePedidoCliente;


/**
 *
 * @author Lucas
 */
public class vntCliente extends javax.swing.JFrame {
    
    
    
    private final DAOManager manager;
    
    
    private ClientesTableModel model;

    /**
     * Creates new form vntCliente
     */
    public vntCliente(DAOManager manager)throws DAOException {
        initComponents();
         this.manager = manager;
         this.model= new ClientesTableModel(manager.getClienteDAO());
         this.model.actualizar();
         this.tablaClientes.setModel(model);
         this.tablaClientes.getSelectionModel().addListSelectionListener(e ->{
              boolean seleccionValida = (tablaClientes.getSelectedRow()!= -1);
              Editar.setEnabled(seleccionValida);
              Borrar.setEnabled(seleccionValida);
         
         });
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        Nuevo = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Guarda = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        detalle = new vistas.DetallePedidoCliente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setBorderPainted(false);
        toolbar.setEnabled(false);

        Nuevo.setText("Nuevo");
        Nuevo.setFocusable(false);
        Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        toolbar.add(Nuevo);

        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.setFocusable(false);
        Editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        toolbar.add(Editar);

        Borrar.setText("Borrar");
        Borrar.setEnabled(false);
        Borrar.setFocusable(false);
        Borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(Borrar);

        Guarda.setText("Guardar");
        Guarda.setEnabled(false);
        Guarda.setFocusable(false);
        Guarda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Guarda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Guarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardaActionPerformed(evt);
            }
        });
        toolbar.add(Guarda);

        Cancelar.setText("Cancelar");
        Cancelar.setEnabled(false);
        Cancelar.setFocusable(false);
        Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        toolbar.add(Cancelar);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel2.add(detalle, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
      detalle.setCliente(null);
      detalle.cargarDatos();
      detalle.setEditable(true);
      Guarda.setEnabled(true);
           Cancelar.setEnabled(true);


    }//GEN-LAST:event_NuevoActionPerformed
       private Cliente getClienteSeleccionado() throws DAOException{
       Long Dni= (Long)tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0);
        
       return manager.getClienteDAO().obtener(Dni);
       
       } 
    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        try {
            Cliente cliente =getClienteSeleccionado();
            detalle.setCliente(cliente);
           detalle.setEditable(true);
           detalle.cargarDatos();
           Guarda.setEnabled(true);
           Cancelar.setEnabled(true);
            
        } catch (DAOException ex) {
            Logger.getLogger(vntCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        detalle.setCliente(null);
        detalle.setEditable(false);
        detalle.cargarDatos();
        tablaClientes.clearSelection();
        
        Guarda.setEnabled(false);
        Cancelar.setEnabled(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void GuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardaActionPerformed
        try {
            detalle.guardar();
            
            Cliente cli =detalle.getCliente();
          
       String hola= detalle.getDniC().getText();
            if(!"".equals(hola)) {
                manager.getClienteDAO().insertar(cli);
            } else manager.getClienteDAO().modificar(cli);
       detalle.setCliente(null);
        detalle.setEditable(false);
        detalle.cargarDatos();
        tablaClientes.clearSelection();
        
        Guarda.setEnabled(false);
        Cancelar.setEnabled(false);
        model.actualizar();
        model.fireTableDataChanged();
        
         
        } catch (DAOException ex) {
            Logger.getLogger(vntCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
         
    }//GEN-LAST:event_GuardaActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vntCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vntCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vntCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vntCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new vntCliente(manager).setVisible(true);
                } catch (DAOException ex) {
                    Logger.getLogger(vntCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Guarda;
    private javax.swing.JButton Nuevo;
    private vistas.DetallePedidoCliente detalle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
