/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Material;
import dao.DAOException;
import java.sql.SQLException;
import dao.DAOManager;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Presupuesto;
import vistas.home;
import vistas.ventVenta;

/**
 *
 * @author Lucas
 */
public class vtnPresupuesto extends javax.swing.JFrame {

    private final DAOManager manager;
    private List<Material> listamateriales = new ArrayList<>();
     private List<Material> listseleccionados = new ArrayList<>();
    int fila = 0;
    float total = 0;

    /**
     * Creates new form presupuesto
     *
     * @throws dao.DAOException
     */
    public vtnPresupuesto(DAOManager manager) throws DAOException {
        initComponents();
        this.manager = manager;
    }

    private vtnPresupuesto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        succes = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonBuscarMaterial = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaMaterialesPedidos = new javax.swing.JTable();
        ingresoidMaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeleccionados = new javax.swing.JTable();
        agregarMaterialesSeleccionados = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();

        jLabel2.setText("se guardoooo!!1");

        aceptar.setText("aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout succesLayout = new javax.swing.GroupLayout(succes.getContentPane());
        succes.getContentPane().setLayout(succesLayout);
        succesLayout.setHorizontalGroup(
            succesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(succesLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, succesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(30, 30, 30))
        );
        succesLayout.setVerticalGroup(
            succesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(succesLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Material ");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botonBuscarMaterial.setText("Buscar");
        botonBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarMaterialActionPerformed(evt);
            }
        });

        tablaMaterialesPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaMaterialesPedidos);

        ingresoidMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoidMaterialActionPerformed(evt);
            }
        });

        tablaSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Cantidad", "Precio Unitario", "Rubro", "Cantidad", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSeleccionados);

        agregarMaterialesSeleccionados.setText("jButton3");
        agregarMaterialesSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMaterialesSeleccionadosActionPerformed(evt);
            }
        });

        calcular.setText("jButton3");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        txttotal.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcular)
                    .addComponent(agregarMaterialesSeleccionados))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(191, 191, 191)
                                .addComponent(ingresoidMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBuscarMaterial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(ingresoidMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBuscarMaterial))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(agregarMaterialesSeleccionados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcular)
                .addGap(20, 20, 20)
                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarMaterialActionPerformed
        String material;
        material = ingresoidMaterial.getText();
        try {
            listamateriales = manager.getMaterialDAO().obtenerTodosxNombre(material);//cambiar obtener todo por nombre

            setTablaMaterialesPeidos();

        } catch (DAOException ex) {
            Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_botonBuscarMaterialActionPerformed

    public void setTablaMaterialesPeidos() {

        tablaMaterialesPedidos.removeAll();

        String[] columnas = new String[]{
            "Nombre",
            "Descripcion",
            "Cantidad",
            "Precio Unitario",
            "Rubro"
        //"Seleccionar"
        };
        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            java.lang.String.class,
            java.lang.Integer.class,
            java.lang.Float.class,
            java.lang.String.class
//JButton.class
        };
        Object[][] datos = new Object[listamateriales.size()][5];
        int i = 0;

        for (Material m : listamateriales) {
            datos[i][0] = m.getNombre();
            datos[i][1] = m.getdescripcion();
            datos[i][2] = m.getStockMaterial();
            datos[i][3] = m.getPrecioUnitario();
            datos[i][4] = m.getRubro();
            i++;
        }

//        datos[0][0]= mat.getNombre();
//        datos[0][1]= mat.getdescripcion();
//        datos[0][2]= mat.getStockMaterial();
//        datos[0][3]= mat.getPrecioUnitario();
//        datos[0][4]= mat.getRubro();
        tablaMaterialesPedidos.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return false;
            }
        });

    }


    private void ingresoidMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoidMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoidMaterialActionPerformed

    private void agregarMaterialesSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMaterialesSeleccionadosActionPerformed

        int seleccionado = tablaMaterialesPedidos.getSelectedRow();
        Material m = listamateriales.get(seleccionado);

        tablaSeleccionados.setValueAt(m.getNombre(), fila, 0);
        tablaSeleccionados.setValueAt(m.getdescripcion(), fila, 1);
        tablaSeleccionados.setValueAt(m.getStockMaterial(), fila, 2);
        tablaSeleccionados.setValueAt(m.getPrecioUnitario(), fila, 3);
        tablaSeleccionados.setValueAt(m.getRubro(), fila, 4);

        fila++;


    }//GEN-LAST:event_agregarMaterialesSeleccionadosActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int tamaño = tablaSeleccionados.getRowCount();

        int i;
        for (i = 0; i < tamaño; i++) {
            //Long sum= Long.valueOf((String.valueOf(tablaSeleccionados.getValueAt(i, 5)))) * Long.valueOf((String.valueOf(tablaSeleccionados.getValueAt(i, 3))));
            Long sum = Long.valueOf(tablaSeleccionados.getValueAt(i, 3).toString()) * Long.valueOf(tablaSeleccionados.getValueAt(i, 5).toString());

            tablaSeleccionados.setValueAt(sum, i, 6);

            if (tablaSeleccionados.getValueAt(i + 1, i) == null) {
                i = tamaño + 1;
            }

            total = total + sum;

        }

        txttotal.setText("$" + total);

    }//GEN-LAST:event_calcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
        java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
        Presupuesto Pre = new Presupuesto(null, sqlDate, total);
        try {
            manager.getPresupuestoDAO().insertar(Pre);
        } catch (DAOException ex) {
            Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
        }

        int i=0;
        for(Material m : listamateriales)
        
        
        
        
        
        succes.setVisible(true);
        succes.setSize(200, 200);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        succes.dispose();

        this.dispose();

        try {

            ventVenta v = new ventVenta(manager);

            v.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarMaterialesSeleccionados;
    private javax.swing.JButton botonBuscarMaterial;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField ingresoidMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog succes;
    private javax.swing.JTable tablaMaterialesPedidos;
    private javax.swing.JTable tablaSeleccionados;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
